org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.11-beta
geckolib_version=Kgc42zo3
mod_id=arksurvivalreturns
mod_name=Ark Survival Returns
mod_license=GPL-3.0-only
mod_version=0.1.0
mod_group_id=dev.nez.arksurvivalreturns
