package dev.nez.arksurvivalreturns.feature.behavior;

import java.util.HashMap;
import java.util.Map;

/**
 * Runtime clip lengths, authored ground speeds and behaviour roles, measured from the runtime
 * GeckoLib models and animations by {@code tools/build_behavior_clips.py}. Generated file: do
 * not edit by hand; rerun the tool after importing clips. Speeds are blocks per second, or NaN
 * for clips without a visible stance phase.
 */
public final class BehaviorClips {
    private static final Map<String, ClipBook> BOOKS = new HashMap<>();

    static {
        BOOKS.put("pteranodon", new ClipBook.Builder("pteranodon")
                .clip("Ptero-Ground-Idle", 67, Double.NaN, true)
                .clip("Ptero-Ground-Move-Fwd", 20, 1.880, true)
                .clip("Ptero-Ground-Attack", 21, Double.NaN, false)
                .clip("Ptero-Ground-Eat", 67, Double.NaN, true)
                .clip("Ptero-Ground-Startled", 40, Double.NaN, false)
                .clip("Ptero-Fly-Fwd", 22, Double.NaN, true)
                .clip("Ptero-Fly-Hover", 18, Double.NaN, true)
                .clip("Ptero-Fly-Attack-Swoop-Loop", 67, Double.NaN, true)
                .clip("Ptero-Fly-Attack-Bite", 22, Double.NaN, false)
                .clip("Ptero-Fly-Attack-Swoop-Out", 103, Double.NaN, false)
                .clip("Ptero-Land", 31, Double.NaN, false)
                .clip("Ptero-Take-Off", 47, Double.NaN, false)
                .clip("Ptero-Torpid-In", 33, Double.NaN, false)
                .clip("Ptero-Torpid-Idle", 67, Double.NaN, true)
                .clip("Ptero-Torpid-Eat", 133, Double.NaN, false)
                .clip("Ptero-Torpid-Out-Tamed", 60, Double.NaN, false)
                .clip("Ptero-Torpid-Out-Wild", 33, Double.NaN, false)
                .clip("Ptero-Ground-Turn-Lft", 20, Double.NaN, true)
                .clip("Ptero-Ground-Turn-Rit", 20, Double.NaN, true)
                .clip("Ptero-Fly-Hurt", 27, Double.NaN, false)
                .clip("Ptero-Fly-Flap", 40, Double.NaN, true)
                .clip("Ptero-Fly-Lft", 22, Double.NaN, true)
                .clip("Ptero-Fly-Rit", 22, Double.NaN, true)
                .clip("Ptero-Fly-Idle", 67, Double.NaN, true)
                .role(ClipRole.FLAP, "Ptero-Fly-Flap")
                .role(ClipRole.FLY_IDLE, "Ptero-Fly-Idle")
                .role(ClipRole.FLY_LEFT, "Ptero-Fly-Lft")
                .role(ClipRole.FLY_RIGHT, "Ptero-Fly-Rit")
                .role(ClipRole.HURT, "Ptero-Fly-Hurt")
                .role(ClipRole.STARTLE, "Ptero-Ground-Startled")
                .role(ClipRole.TURN_LEFT, "Ptero-Ground-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Ptero-Ground-Turn-Rit")
                .build());
        BOOKS.put("velociraptor", new ClipBook.Builder("velociraptor")
                .clip("Raptor-Idle", 60, Double.NaN, true)
                .clip("Raptor-Move-Fwd", 21, 5.983, true)
                .clip("Raptor-Attack", 13, Double.NaN, false)
                .clip("Raptor-Charge-Fwd", 13, 10.684, true)
                .clip("Raptor-Eat-Additive", 30, Double.NaN, true)
                .clip("Raptor-Call", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Raptor-Torpid-In", 40, Double.NaN, false)
                .clip("Raptor-Torpid", 67, Double.NaN, true)
                .clip("Raptor-Torpid-Eat", 67, Double.NaN, false)
                .clip("Raptor-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Raptor-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Raptor-Startled", 16, Double.NaN, false)
                .clip("Raptor-Hurt-Big", 13, Double.NaN, false)
                .role(ClipRole.HURT, "Raptor-Hurt-Big")
                .role(ClipRole.STARTLE, "Raptor-Startled")
                .build());
        BOOKS.put("argentavis", new ClipBook.Builder("argentavis")
                .clip("Argentavis-Ground-Idle", 40, Double.NaN, true)
                .clip("Argentavis-Ground-Move-Fwd", 27, 2.640, true)
                .clip("Argentavis-Ground-Attack", 27, Double.NaN, false)
                .clip("Argentavis-Ground-Eat", 67, Double.NaN, true)
                .clip("Argentavis-Ground-Startled", 27, Double.NaN, false)
                .clip("Argentavis-Fly-Fwd", 22, Double.NaN, true)
                .clip("Argentavis-Fly-Hover", 17, Double.NaN, true)
                .clip("Argentavis-Fly-Attack-Claw", 20, Double.NaN, false)
                .clip("Argentavis-Fly-Attack-Swoop-Out", 20, Double.NaN, false)
                .clip("Argentavis-Land", 27, Double.NaN, false)
                .clip("Argentavis-Take-Off", 27, Double.NaN, false)
                .clip("Argentavis-Torpid-In", 33, Double.NaN, false)
                .clip("Argentavis-Torpid-Idle", 67, Double.NaN, true)
                .clip("Argentavis-Torpid-Eat", 67, Double.NaN, false)
                .clip("Argentavis-Torpid-Out-Tamed", 53, Double.NaN, false)
                .clip("Argentavis-Torpid-Out-Wild", 33, Double.NaN, false)
                .clip("Argentavis-Fly-Hurt-Big", 20, Double.NaN, false)
                .clip("Argentavis-Fly-Lft", 22, Double.NaN, true)
                .clip("Argentavis-Fly-Rit", 22, Double.NaN, true)
                .clip("Argentavis-Fly-Idle", 40, Double.NaN, true)
                .role(ClipRole.FLY_IDLE, "Argentavis-Fly-Idle")
                .role(ClipRole.FLY_LEFT, "Argentavis-Fly-Lft")
                .role(ClipRole.FLY_RIGHT, "Argentavis-Fly-Rit")
                .role(ClipRole.HURT, "Argentavis-Fly-Hurt-Big")
                .role(ClipRole.STARTLE, "Argentavis-Ground-Startled")
                .build());
        BOOKS.put("triceratops", new ClipBook.Builder("triceratops")
                .clip("Trike-Idle", 67, Double.NaN, true)
                .clip("Trike-Move-Fwd", 47, 1.552, true)
                .clip("Trike-Attack-Horn", 20, Double.NaN, false)
                .clip("Trike-Charge-Fwd", 16, 4.683, true)
                .clip("Trike-Graze", 133, Double.NaN, true)
                .clip("Trike-Startled", 27, Double.NaN, false)
                .clip("Trike-Sleeping", 400, Double.NaN, true)
                .clip("Trike-Torpid-In", 53, Double.NaN, false)
                .clip("Trike-Torpid", 67, Double.NaN, true)
                .clip("Trike-Torpid-Eat", 67, Double.NaN, false)
                .clip("Trike-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Trike-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Trike-Turn-Lft", 47, Double.NaN, true)
                .clip("Trike-Turn-Rit", 47, Double.NaN, true)
                .clip("Trike-Hurt-Big-Rit", 40, Double.NaN, false)
                .role(ClipRole.HURT, "Trike-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Trike-Startled")
                .role(ClipRole.TURN_LEFT, "Trike-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Trike-Turn-Rit")
                .build());
        BOOKS.put("therizinosaurus", new ClipBook.Builder("therizinosaurus")
                .clip("Therizinosaurus-Idle", 67, Double.NaN, true)
                .clip("Therizinosaurus-Move-Fwd", 29, 4.507, true)
                .clip("Therizinosaurus-Attack-Claw", 20, Double.NaN, false)
                .clip("Therizinosaurus-Charge-Fwd", 16, 12.311, true)
                .clip("Therizinosaurus-Eat", 133, Double.NaN, true)
                .clip("Therizinosaurus-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Therizinosaurus-Torpid-In", 40, Double.NaN, false)
                .clip("Therizinosaurus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Therizinosaurus-Torpid-Eat", 67, Double.NaN, false)
                .clip("Therizinosaurus-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Therizinosaurus-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Therizinosaurus-Move-Lft", 29, 4.498, true)
                .clip("Therizinosaurus-Move-Rit", 29, 4.480, true)
                .clip("Therizinosaurus-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Therizinosaurus-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Therizinosaurus-Startled")
                .role(ClipRole.TURN_LEFT, "Therizinosaurus-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Therizinosaurus-Move-Rit")
                .build());
        BOOKS.put("brontosaurus", new ClipBook.Builder("brontosaurus")
                .clip("Sauropod-Idle", 133, Double.NaN, true)
                .clip("Sauropod-Move-Fwd", 67, 0.928, true)
                .clip("Sauropod-Attack-FootStomp", 53, Double.NaN, false)
                .clip("Sauropod-Charge-Fwd", 28, 2.244, true)
                .clip("Sauropod-Graze", 200, Double.NaN, true)
                .clip("Sauropod-Startled-Lft", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Sauropod-Torpid-In", 73, Double.NaN, false)
                .clip("Sauropod-Torpid", 67, Double.NaN, true)
                .clip("Sauropod-Torpid-Eat", 67, Double.NaN, false)
                .clip("Sauropod-Torpid-Out-Tamed", 100, Double.NaN, false)
                .clip("Sauropod-Torpid-Out-Wild", 53, Double.NaN, false)
                .clip("Sauropod-Turn-Lft", 55, Double.NaN, true)
                .clip("Sauropod-Turn-Rit", 55, Double.NaN, true)
                .clip("Sauropod-Hurt-Lft", 27, Double.NaN, false)
                .role(ClipRole.HURT, "Sauropod-Hurt-Lft")
                .role(ClipRole.STARTLE, "Sauropod-Startled-Lft")
                .role(ClipRole.TURN_LEFT, "Sauropod-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Sauropod-Turn-Rit")
                .build());
        BOOKS.put("tyrannosaurus", new ClipBook.Builder("tyrannosaurus")
                .clip("Rex-Idle", 107, Double.NaN, true)
                .clip("Rex-Move-Fwd", 41, 7.595, true)
                .clip("Rex-Bite2", 28, Double.NaN, false)
                .clip("Rex-Charge-Fwd", 18, 21.605, true)
                .clip("Rex-Eat-Additive", 40, Double.NaN, true)
                .clip("Rex-Roar", 89, Double.NaN, false)
                .clip("Rex-Sleeping", 27, Double.NaN, true)
                .clip("Rex-Torpid-In", 40, Double.NaN, false)
                .clip("Rex-Torpid", 67, Double.NaN, true)
                .clip("Rex-Torpid-Eat", 67, Double.NaN, false)
                .clip("Rex-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Rex-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Rex-Move-Lft", 40, 9.174, true)
                .clip("Rex-Move-Rit", 40, 7.563, true)
                .clip("Rex-Startled-Lft", 33, Double.NaN, false)
                .clip("Rex-Hurt-Big-Lft", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Rex-Hurt-Big-Lft")
                .role(ClipRole.STARTLE, "Rex-Startled-Lft")
                .role(ClipRole.TURN_LEFT, "Rex-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Rex-Move-Rit")
                .build());
        BOOKS.put("giganotosaurus", new ClipBook.Builder("giganotosaurus")
                .clip("Giganotosaurus-Idle", 67, Double.NaN, true)
                .clip("Giganotosaurus-Move-Fwd", 31, 15.783, true)
                .clip("Giganotosaurus-Attack-Bite", 20, Double.NaN, false)
                .clip("Giganotosaurus-Charge-Fwd", 14, 49.014, true)
                .clip("Giganotosaurus-Eat", 133, Double.NaN, true)
                .clip("Giganotosaurus-Roar", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Giganotosaurus-Torpid-In", 40, Double.NaN, false)
                .clip("Giganotosaurus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Giganotosaurus-Torpid-Eat", 67, Double.NaN, false)
                .clip("Giganotosaurus-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Giganotosaurus-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Giganotosaurus-Move-Lft", 30, 16.320, true)
                .clip("Giganotosaurus-Move-Rit", 30, 16.789, true)
                .clip("Giganotosaurus-Startled", 27, Double.NaN, false)
                .clip("Giganotosaurus-Hurt-Small-Rit", 10, Double.NaN, false)
                .role(ClipRole.HURT, "Giganotosaurus-Hurt-Small-Rit")
                .role(ClipRole.STARTLE, "Giganotosaurus-Startled")
                .role(ClipRole.TURN_LEFT, "Giganotosaurus-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Giganotosaurus-Move-Rit")
                .build());
        BOOKS.put("titanosaur", new ClipBook.Builder("titanosaur")
                .clip("Titanosaur-Idle", 333, Double.NaN, true)
                .clip("Titanosaur-Move-Fwd", 63, 4.955, true)
                .clip("Titanosaur-Attack-Footstomp", 53, Double.NaN, false)
                .clip("Titanosaur-Charge-Fwd", 37, 8.488, true)
                .clip("Titanosaur-Eat", 200, Double.NaN, true)
                .clip("Titanosaur-Startled-Lft", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Titanosaur-Torpid-In", 67, Double.NaN, false)
                .clip("Titanosaur-Torpid-Idle", 67, Double.NaN, true)
                .clip("Titanosaur-Torpid-Eat", 67, Double.NaN, false)
                .clip("Titanosaur-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Titanosaur-Torpid-Out-Wild", 27, Double.NaN, false)
                .clip("Titanosaur-Move-Lft", 56, 5.630, true)
                .clip("Titanosaur-Move-Rit", 56, 5.624, true)
                .clip("Titanosaur-Hurt-Lft", 27, Double.NaN, false)
                .role(ClipRole.HURT, "Titanosaur-Hurt-Lft")
                .role(ClipRole.STARTLE, "Titanosaur-Startled-Lft")
                .role(ClipRole.TURN_LEFT, "Titanosaur-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Titanosaur-Move-Rit")
                .build());
        BOOKS.put("spinosaurus", new ClipBook.Builder("spinosaurus")
                .clip("Spino-Idle", 67, Double.NaN, true)
                .clip("Spino-Move-Fwd", 20, 6.967, true)
                .clip("Spino-Attack-Bite", 20, Double.NaN, false)
                .clip("Spino-Charge-Fwd", 15, 17.812, true)
                .clip("Spino-Eat", 30, Double.NaN, true)
                .clip("Spino-Roar", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Spino-Torpid-In", 40, Double.NaN, false)
                .clip("Spino-Torpid-Idle", 67, Double.NaN, true)
                .clip("Spino-Torpid-Eat", 67, Double.NaN, false)
                .clip("Spino-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Spino-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Spino-Move-Lft", 20, 7.020, true)
                .clip("Spino-Move-Rit", 23, 6.727, true)
                .clip("Spino-Startled", 27, Double.NaN, false)
                .clip("Spino-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Spino-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Spino-Startled")
                .role(ClipRole.TURN_LEFT, "Spino-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Spino-Move-Rit")
                .build());
        BOOKS.put("parasaur", new ClipBook.Builder("parasaur")
                .clip("Para-Idle", 67, Double.NaN, true)
                .clip("Para-Move-Fwd", 27, 2.386, true)
                .clip("Para-Attack-Bite", 20, Double.NaN, false)
                .clip("Para-Charge-Fwd", 19, 7.409, true)
                .clip("Para-Graze", 133, Double.NaN, true)
                .clip("Para-Roar-Alert", 50, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Para-Torpid-In", 40, Double.NaN, false)
                .clip("Para-Torpid", 67, Double.NaN, true)
                .clip("Para-Torpid-Eat", 67, Double.NaN, false)
                .clip("Para-Torpid-Out-Tamed", 60, Double.NaN, false)
                .clip("Para-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Para-Turn-Lft", 38, Double.NaN, true)
                .clip("Para-Turn-Rit", 38, Double.NaN, true)
                .clip("Para-Turret-Check-Idle", 40, Double.NaN, false)
                .clip("Para-Startled", 50, Double.NaN, false)
                .clip("Para-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Para-Hurt-Big-Rit")
                .role(ClipRole.LOOK, "Para-Turret-Check-Idle")
                .role(ClipRole.STARTLE, "Para-Startled")
                .role(ClipRole.TURN_LEFT, "Para-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Para-Turn-Rit")
                .build());
        BOOKS.put("ceratosaurus", new ClipBook.Builder("ceratosaurus")
                .clip("Ceratosaurus_Idle", 120, Double.NaN, true)
                .clip("Ceratosaurus_MoveFWD", 36, 3.643, true)
                .clip("Cerato_Attack_Bite1", 23, Double.NaN, false)
                .clip("Ceratosaurus_ChargeFWD_NOBOOST", 19, 20.051, true)
                .clip("Ceratosaurus_Eat", 37, Double.NaN, true)
                .clip("Ceratosaurus_Roar1", 60, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Ceratosaurus_Move_TurningLeft", 36, Double.NaN, true)
                .clip("Ceratosaurus_Move_TurningRight", 36, Double.NaN, true)
                .clip("Ceratosaurus_Startled", 50, Double.NaN, false)
                .clip("Ceratosaurus_Aggro", 73, Double.NaN, true)
                .role(ClipRole.STARTLE, "Ceratosaurus_Startled")
                .role(ClipRole.THREAT, "Ceratosaurus_Aggro")
                .role(ClipRole.TURN_LEFT, "Ceratosaurus_Move_TurningLeft")
                .role(ClipRole.TURN_RIGHT, "Ceratosaurus_Move_TurningRight")
                .build());
        BOOKS.put("dilophosaur", new ClipBook.Builder("dilophosaur")
                .clip("Dilo-Idle", 67, Double.NaN, true)
                .clip("Dilo-Move-Fwd", 18, 2.222, true)
                .clip("Dilo-Attack-Bite", 20, Double.NaN, false)
                .clip("Dilo-Charge-Fwd", 11, 3.476, true)
                .clip("Dilo-Eat", 50, Double.NaN, true)
                .clip("Dilo-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Dilo-Torpid-In", 40, Double.NaN, false)
                .clip("Dilo-Torpid", 67, Double.NaN, true)
                .clip("Dilo-Torpid-Eat", 67, Double.NaN, false)
                .clip("Dilo-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Dilo-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Dilo-Turn-Lft", 20, Double.NaN, true)
                .clip("Dilo-Turn-Rit", 20, Double.NaN, true)
                .clip("Dilo-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Dilo-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Dilo-Startled")
                .role(ClipRole.TURN_LEFT, "Dilo-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Dilo-Turn-Rit")
                .build());
        BOOKS.put("acrocanthosaurus", new ClipBook.Builder("acrocanthosaurus")
                .clip("Acro_Idle", 139, Double.NaN, true)
                .clip("Acro_Move_Walk_FWD", 42, 8.438, true)
                .clip("Acro_Attack_Bite", 71, Double.NaN, false)
                .clip("Acro_Move_Charge_FWD", 28, 15.715, true)
                .clip("Acro_Eat", 83, Double.NaN, true)
                .clip("Acro_Attack_Roar", 124, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Acro_Torp_In", 167, Double.NaN, false)
                .clip("Acro_Torp_Loop", 80, Double.NaN, true)
                .clip("Acro_Torp_Eat", 83, Double.NaN, false)
                .clip("Acro_Torp_Out", 118, Double.NaN, false)
                .clip("Acro_Move_Walk_LEFT", 42, 8.440, true)
                .clip("Acro_Move_Walk_RIGHT", 42, 8.466, true)
                .role(ClipRole.TURN_LEFT, "Acro_Move_Walk_LEFT")
                .role(ClipRole.TURN_RIGHT, "Acro_Move_Walk_RIGHT")
                .build());
        BOOKS.put("allosaurus", new ClipBook.Builder("allosaurus")
                .clip("Allosaurus-Idle", 46, Double.NaN, true)
                .clip("Allosaurus-Move-Fwd", 25, 6.716, true)
                .clip("Allosaurus-Attack-Bite", 20, Double.NaN, false)
                .clip("Allosaurus-Charge-Fwd", 15, 22.787, true)
                .clip("Allosaurus-Eat-Additive", 33, Double.NaN, true)
                .clip("Allosaurus-Roar_Anim", 39, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Allosaurus-Torpid-In", 39, Double.NaN, false)
                .clip("Allosaurus-Torpid-Idle", 66, Double.NaN, true)
                .clip("Allosaurus-Torpid-Eat", 66, Double.NaN, false)
                .clip("Allosaurus-Torpid-Out-Tamed", 66, Double.NaN, false)
                .clip("Allosaurus-Torpid-Out-Wild", 39, Double.NaN, false)
                .clip("Allosaurus-Move-Lft", 28, 5.962, true)
                .clip("Allosaurus-Move-Rit", 28, 5.964, true)
                .clip("Allosaurus-Startled", 26, Double.NaN, false)
                .clip("Allosaurus-Hurt-Small-Lft", 9, Double.NaN, false)
                .role(ClipRole.HURT, "Allosaurus-Hurt-Small-Lft")
                .role(ClipRole.STARTLE, "Allosaurus-Startled")
                .role(ClipRole.TURN_LEFT, "Allosaurus-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Allosaurus-Move-Rit")
                .build());
        BOOKS.put("ankylosaurus", new ClipBook.Builder("ankylosaurus")
                .clip("Ankylo-Idle", 67, Double.NaN, true)
                .clip("Ankylo-Move-Fwd", 22, 1.900, true)
                .clip("Ankylo-Attack-Tail-Sweep", 33, Double.NaN, false)
                .clip("Ankylo-Charge-Fwd", 12, 5.105, true)
                .clip("Ankylo-Graze", 133, Double.NaN, true)
                .clip("Ankylo-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Ankylo-Torpid-In", 40, Double.NaN, false)
                .clip("Ankylo-Torpid", 67, Double.NaN, true)
                .clip("Ankylo-Torpid-Eat", 67, Double.NaN, false)
                .clip("Ankylo-Torpid-Out-Tamed", 50, Double.NaN, false)
                .clip("Ankylo-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Ankylo-Turn-Lft", 22, Double.NaN, true)
                .clip("Ankylo-Turn-Rit", 22, Double.NaN, true)
                .clip("Ankylo-Idle-Aggressive", 67, Double.NaN, true)
                .clip("Ankylo-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Ankylo-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Ankylo-Startled")
                .role(ClipRole.THREAT, "Ankylo-Idle-Aggressive")
                .role(ClipRole.TURN_LEFT, "Ankylo-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Ankylo-Turn-Rit")
                .build());
        BOOKS.put("carnotaurus", new ClipBook.Builder("carnotaurus")
                .clip("Carno-Idle", 67, Double.NaN, true)
                .clip("Carno-Move-Fwd", 24, 5.427, true)
                .clip("Carno-Attack-Bite", 20, Double.NaN, false)
                .clip("Carno-Charge-Fwd", 14, 11.025, true)
                .clip("Carno-Eat", 37, Double.NaN, true)
                .clip("Carno-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Carno-Torpid-In", 40, Double.NaN, false)
                .clip("Carno-Torpid-Idle", 67, Double.NaN, true)
                .clip("Carno-Torpid-Eat", 67, Double.NaN, false)
                .clip("Carno-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Carno-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Carno-Move-Lft", 24, 5.612, true)
                .clip("Carno-Move-Rit", 24, 5.633, true)
                .clip("Carno-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Carno-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Carno-Startled")
                .role(ClipRole.TURN_LEFT, "Carno-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Carno-Move-Rit")
                .build());
        BOOKS.put("pegomastax", new ClipBook.Builder("pegomastax")
                .clip("Pegomastax-Idle", 67, Double.NaN, true)
                .clip("Pegomastax-Move-Fwd", 20, 1.355, true)
                .clip("Pegomastax-Attack-Bite", 17, Double.NaN, false)
                .clip("Pegomastax-Biped-Charge-Fwd", 9, 3.836, true)
                .clip("Pegomastax-Eat", 67, Double.NaN, true)
                .clip("Pegomastax-Roar", 40, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Pegomastax-Torpid-In", 40, Double.NaN, false)
                .clip("Pegomastax-Torpid-Idle", 67, Double.NaN, true)
                .clip("Pegomastax-Torpid-Eat", 67, Double.NaN, false)
                .clip("Pegomastax-Torpid-Out-Tamed", 73, Double.NaN, false)
                .clip("Pegomastax-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Pegomastax-Move-Lft", 20, 1.356, true)
                .clip("Pegomastax-Move-Rit", 20, 1.356, true)
                .clip("Pegomastax-Startled", 40, Double.NaN, false)
                .clip("Pegomastax-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Pegomastax-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Pegomastax-Startled")
                .role(ClipRole.TURN_LEFT, "Pegomastax-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Pegomastax-Move-Rit")
                .build());
        BOOKS.put("lystrosaurus", new ClipBook.Builder("lystrosaurus")
                .clip("Lystrosaurus-Idle", 67, Double.NaN, true)
                .clip("Lystrosaurus-Move-Fwd", 20, 0.628, true)
                .clip("Lystrosaurus-Attack-Bite", 20, Double.NaN, false)
                .clip("Lystrosaurus-Charge-Fwd", 11, 1.277, true)
                .clip("Lystrosaurus-Eat", 67, Double.NaN, true)
                .clip("Lystrosaurus-Startled", 20, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Lystrosaurus-Torpid-In", 40, Double.NaN, false)
                .clip("Lystrosaurus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Lystrosaurus-Torpid-Eat", 67, Double.NaN, false)
                .clip("Lystrosaurus-Torpid-Out-Tamed", 40, Double.NaN, false)
                .clip("Lystrosaurus-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Lystrosaurus-Move-Lft", 20, 0.628, true)
                .clip("Lystrosaurus-Move-Rit", 20, 0.628, true)
                .clip("Lystrosaurus-Hurt-Small", 10, Double.NaN, false)
                .role(ClipRole.HURT, "Lystrosaurus-Hurt-Small")
                .role(ClipRole.STARTLE, "Lystrosaurus-Startled")
                .role(ClipRole.TURN_LEFT, "Lystrosaurus-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Lystrosaurus-Move-Rit")
                .build());
        BOOKS.put("cnidaria", new ClipBook.Builder("cnidaria")
                .clip("Cnidaria-Idle", 67, Double.NaN, true)
                .clip("Cnidaria-Shock", 20, Double.NaN, true)
                .clip("Cnidaria-Wide-Idle", 256, Double.NaN, false)
                .clip("Cnidaria-Hurt", 13, Double.NaN, false)
                .role(ClipRole.HURT, "Cnidaria-Hurt")
                .build());
        BOOKS.put("plesiosaur", new ClipBook.Builder("plesiosaur")
                .clip("Plesiosaur-Idle", 67, Double.NaN, true)
                .clip("Plesiosaur-Move-Fwd", 167, Double.NaN, true)
                .clip("Plesiosaur-Attack-Bite", 20, Double.NaN, false)
                .clip("Plesiosaur-Eat", 20, Double.NaN, true)
                .clip("Plesiosaur-Torpid-In", 20, Double.NaN, false)
                .clip("Plesiosaur-Torpid-Idle", 67, Double.NaN, true)
                .clip("Plesiosaur-Torpid-Eat", 133, Double.NaN, false)
                .clip("Plesiosaur-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Plesiosaur-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Plesiosaur-Move-Lft", 167, Double.NaN, true)
                .clip("Plesiosaur-Move-Rit", 167, Double.NaN, true)
                .clip("Plesiosaur-Hurt-Big-Lft", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Plesiosaur-Hurt-Big-Lft")
                .role(ClipRole.SWIM_LEFT, "Plesiosaur-Move-Lft")
                .role(ClipRole.SWIM_RIGHT, "Plesiosaur-Move-Rit")
                .build());
        BOOKS.put("megalodon", new ClipBook.Builder("megalodon")
                .clip("Megalodon-Idle", 67, Double.NaN, true)
                .clip("Megalodon-Swim-Fwd", 44, Double.NaN, true)
                .clip("Megalodon-Attack-Bite", 27, Double.NaN, false)
                .clip("Megalodon-Eat", 33, Double.NaN, true)
                .clip("Megalodon-Torpid-In", 20, Double.NaN, false)
                .clip("Megalodon-Torpid", 67, Double.NaN, true)
                .clip("Megalodon-Torpid-Eat", 67, Double.NaN, false)
                .clip("Megalodon-Torpid-Out-Tamed", 40, Double.NaN, false)
                .clip("Megalodon-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Megalodon-Swim-Lft", 44, Double.NaN, true)
                .clip("Megalodon-Swim-Rit", 44, Double.NaN, true)
                .clip("Megalodon-Hurt-Big-Rit", 27, Double.NaN, false)
                .role(ClipRole.HURT, "Megalodon-Hurt-Big-Rit")
                .role(ClipRole.SWIM_LEFT, "Megalodon-Swim-Lft")
                .role(ClipRole.SWIM_RIGHT, "Megalodon-Swim-Rit")
                .build());
        BOOKS.put("liopleurodon", new ClipBook.Builder("liopleurodon")
                .clip("Liopleurodon-Idle", 67, Double.NaN, true)
                .clip("Liopleurodon-Swim-Fwd", 67, Double.NaN, true)
                .clip("Liopleurodon-Attack-Chomp", 27, Double.NaN, false)
                .clip("Liopleurodon-Swim-Charge-Fwd", 67, Double.NaN, true)
                .clip("Liopleurodon-Torpid-Eat", 133, Double.NaN, false)
                .clip("Liopleurodon-Spin", 133, Double.NaN, true)
                .clip("Liopleurodon-Torpid-In", 20, Double.NaN, false)
                .clip("Liopleurodon-Torpid-Idle", 67, Double.NaN, true)
                .clip("Liopleurodon-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("Liopleurodon-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Liopleurodon-Swim-Lft", 67, Double.NaN, true)
                .clip("Liopleurodon-Swim-Rit", 67, Double.NaN, true)
                .clip("Liopleurodon-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Liopleurodon-Hurt-Big")
                .role(ClipRole.SWIM_LEFT, "Liopleurodon-Swim-Lft")
                .role(ClipRole.SWIM_RIGHT, "Liopleurodon-Swim-Rit")
                .build());
        BOOKS.put("mosasaurus", new ClipBook.Builder("mosasaurus")
                .clip("Mosasaurus-Idle", 67, Double.NaN, true)
                .clip("Mosasaurus-Swim-Fwd", 148, Double.NaN, true)
                .clip("Mosasaurus-Attack-Bite", 27, Double.NaN, false)
                .clip("Mosasaurus-Charge-Fwd", 61, Double.NaN, true)
                .clip("Mosasaurus-Eat", 33, Double.NaN, true)
                .clip("Mosasaurus-Torpid-In", 20, Double.NaN, false)
                .clip("Mosasaurus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Mosasaurus-Torpid-Eat", 67, Double.NaN, false)
                .clip("Mosasaurus-Torpid-Out-Tamed", 40, Double.NaN, false)
                .clip("Mosasaurus-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Mosasaurus-Swim-Lft", 148, Double.NaN, true)
                .clip("Mosasaurus-Swim-Rit", 148, Double.NaN, true)
                .clip("Mosasaurus-Hurt-Big-Lft", 27, Double.NaN, false)
                .role(ClipRole.HURT, "Mosasaurus-Hurt-Big-Lft")
                .role(ClipRole.SWIM_LEFT, "Mosasaurus-Swim-Lft")
                .role(ClipRole.SWIM_RIGHT, "Mosasaurus-Swim-Rit")
                .build());
        BOOKS.put("tusoteuthis", new ClipBook.Builder("tusoteuthis")
                .clip("Tusoteuthis-Idle", 222, Double.NaN, true)
                .clip("Tusoteuthis-Swim-Fwd", 190, Double.NaN, true)
                .clip("Tusoteuthis-Attack-Bite", 57, Double.NaN, false)
                .clip("Tusoteuthis-Eat", 133, Double.NaN, true)
                .clip("Tusoteuthis-Attack-Crush-Loop", 53, Double.NaN, true)
                .clip("Tusoteuthis-Torpid-In", 20, Double.NaN, false)
                .clip("Tusoteuthis-Torpid-Idle", 133, Double.NaN, true)
                .clip("Tusoteuthis-Torpid-Out-Tamed", 33, Double.NaN, false)
                .clip("Tusoteuthis-Torpid-Out-Wild", 20, Double.NaN, false)
                .clip("Tusoteuthis-Swim-Lft", 190, Double.NaN, true)
                .clip("Tusoteuthis-Swim-Rit", 190, Double.NaN, true)
                .clip("Tusoteuthis-Hurt-Big", 40, Double.NaN, false)
                .role(ClipRole.HURT, "Tusoteuthis-Hurt-Big")
                .role(ClipRole.SWIM_LEFT, "Tusoteuthis-Swim-Lft")
                .role(ClipRole.SWIM_RIGHT, "Tusoteuthis-Swim-Rit")
                .build());
        BOOKS.put("kaprosuchus", new ClipBook.Builder("kaprosuchus")
                .clip("Kaprosuchus-Idle", 67, Double.NaN, true)
                .clip("Kaprosuchus-Move-Fwd", 26, 1.802, true)
                .clip("Kaprosuchus-Attack-Bite", 20, Double.NaN, false)
                .clip("Kaprosuchus-Charge-Fwd", 13, 6.971, true)
                .clip("Kaprosuchus-Eat", 67, Double.NaN, true)
                .clip("Kaprosuchus-Startle", 27, Double.NaN, false)
                .clip("Kaprosuchus-Swim-Idle", 100, Double.NaN, true)
                .clip("Kaprosuchus-Swim-Fwd", 44, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Kaprosuchus-Torpid-In", 20, Double.NaN, false)
                .clip("Kaprosuchus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Kaprosuchus-Torpid-Eat", 67, Double.NaN, false)
                .clip("Kaprosuchus-Torpid-Out-Tamed", 40, Double.NaN, false)
                .clip("Kaprosuchus-Torpid-Out-Wild", 20, Double.NaN, false)
                .clip("Kaprosuchus-Move-Lft", 26, 1.803, true)
                .clip("Kaprosuchus-Move-Rit", 26, 1.794, true)
                .clip("Kaprosuchus-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Kaprosuchus-Hurt-Big")
                .role(ClipRole.STARTLE, "Kaprosuchus-Startle")
                .role(ClipRole.TURN_LEFT, "Kaprosuchus-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Kaprosuchus-Move-Rit")
                .build());
        BOOKS.put("sarco", new ClipBook.Builder("sarco")
                .clip("Sarco-Ground-Idle", 67, Double.NaN, true)
                .clip("Sarco-Ground-Move-Fwd", 37, 1.309, true)
                .clip("Sarco-Ground-Attack-Bite", 20, Double.NaN, false)
                .clip("Sarco-Ground-Charge-Fwd", 16, 8.812, true)
                .clip("Sarco-Ground-Eat-Additive", 30, Double.NaN, true)
                .clip("Sarco-Ground-Attack-Lunge", 21, Double.NaN, true)
                .clip("Sarco-Swim-Idle", 64, Double.NaN, true)
                .clip("Sarco-Swim-Fwd", 16, Double.NaN, true)
                .clip("Sarco-Swim-Charge-Fwd", 12, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Sarco-Ground-Torpid-In", 40, Double.NaN, false)
                .clip("Sarco-Ground-Torpid-Idle", 67, Double.NaN, true)
                .clip("Sarco-Ground-Torpid-Eat", 133, Double.NaN, false)
                .clip("Sarco-Ground-Torpid-Out-Tamed", 40, Double.NaN, false)
                .clip("Sarco-Ground-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Sarco-Ground-Turn-Lft", 33, Double.NaN, true)
                .clip("Sarco-Ground-Turn-Rit", 33, Double.NaN, true)
                .clip("Sarco-Ground-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Sarco-Ground-Hurt-Big")
                .role(ClipRole.TURN_LEFT, "Sarco-Ground-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Sarco-Ground-Turn-Rit")
                .build());
        BOOKS.put("deinosuchus", new ClipBook.Builder("deinosuchus")
                .clip("Deinosuchus_Idle", 83, Double.NaN, true)
                .clip("Deinosuchus_Move_FWD", 47, 1.337, true)
                .clip("Deinosuchus_Attack_Bite", 30, Double.NaN, false)
                .clip("Deinosuchus_Charge_FWD", 31, 3.007, true)
                .clip("Deinosuchus_Eat", 99, Double.NaN, true)
                .clip("Deinosuchus_Attack_Hiss", 83, Double.NaN, true)
                .clip("Deinosuchus_Swim_Idle", 102, Double.NaN, true)
                .clip("Deinosuchus_Swim_Move_FWD", 27, Double.NaN, true)
                .clip("Deinosuchus_Swim_Charge_FWD", 30, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Deinosuchus_Torp_In", 83, Double.NaN, false)
                .clip("Deinosuchus_Move_TurnLeft", 24, Double.NaN, true)
                .clip("Deinosuchus_Move_TurnRight", 24, Double.NaN, true)
                .clip("Deinosuchus_Basking_Start", 66, Double.NaN, false)
                .clip("Deinosuchus_Basking_Idle", 17, Double.NaN, true)
                .clip("Deinosuchus_Basking_End", 42, Double.NaN, false)
                .role(ClipRole.REST, "Deinosuchus_Basking_Idle")
                .role(ClipRole.SETTLE, "Deinosuchus_Basking_Start")
                .role(ClipRole.TURN_LEFT, "Deinosuchus_Move_TurnLeft")
                .role(ClipRole.TURN_RIGHT, "Deinosuchus_Move_TurnRight")
                .role(ClipRole.WAKE, "Deinosuchus_Basking_End")
                .build());
        BOOKS.put("titanoboa", new ClipBook.Builder("titanoboa")
                .clip("BoaFrill-Idle", 67, Double.NaN, true)
                .clip("BoaFrill-Move-Fwd", 33, 1.190, true)
                .clip("BoaFrill-Attack-Lunge", 33, Double.NaN, false)
                .clip("BoaFrill-Charge-Fwd", 13, Double.NaN, true)
                .clip("BoaFrill-Eat-Additive", 33, Double.NaN, true)
                .clip("BoaFrill-Startled", 33, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("BoaFrill-Turn-Lft", 33, Double.NaN, true)
                .clip("BoaFrill-Turn-Rit", 33, Double.NaN, true)
                .clip("BoaFrill-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "BoaFrill-Hurt-Big")
                .role(ClipRole.STARTLE, "BoaFrill-Startled")
                .role(ClipRole.TURN_LEFT, "BoaFrill-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "BoaFrill-Turn-Rit")
                .build());
        BOOKS.put("megalocerus", new ClipBook.Builder("megalocerus")
                .clip("Stag-Idle", 67, Double.NaN, true)
                .clip("Stag-Move-Fwd", 21, 1.097, true)
                .clip("Stag-Attack-Gore", 20, Double.NaN, false)
                .clip("Stag-Charge-Fwd", 10, 4.802, true)
                .clip("Stag-Graze", 133, Double.NaN, true)
                .clip("Stag-Startled", 20, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Stag-Torpid-In", 40, Double.NaN, false)
                .clip("Stag-Torpid-Idle", 67, Double.NaN, true)
                .clip("Stag-Torpid-Eat", 67, Double.NaN, false)
                .clip("Stag-Torpid-Out-Tamed", 60, Double.NaN, false)
                .clip("Stag-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Stag-Move-Lft", 21, 1.097, true)
                .clip("Stag-Move-Rit", 21, 1.097, true)
                .clip("Stag-Look-Around", 133, Double.NaN, false)
                .clip("Stag-Poop", 20, Double.NaN, false)
                .clip("Stag-Hurt-Big-Lft", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Stag-Hurt-Big-Lft")
                .role(ClipRole.LOOK, "Stag-Look-Around")
                .role(ClipRole.POOP, "Stag-Poop")
                .role(ClipRole.STARTLE, "Stag-Startled")
                .role(ClipRole.TURN_LEFT, "Stag-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Stag-Move-Rit")
                .build());
        BOOKS.put("unicorn", new ClipBook.Builder("unicorn")
                .clip("Equus-Idle2", 225, Double.NaN, true)
                .clip("Equus-Move-Fwd", 53, 0.775, true)
                .clip("Equus-Attack-Buck", 25, Double.NaN, false)
                .clip("Equus-Charge-Fwd", 8, 8.498, true)
                .clip("Equus-Eat", 83, Double.NaN, true)
                .clip("Equus-Roar", 75, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Equus-Torpid-In", 50, Double.NaN, false)
                .clip("Equus-Torpid-Idle", 83, Double.NaN, true)
                .clip("Equus-Torpid-Eat", 83, Double.NaN, false)
                .clip("Equus-Torpid-Out-Tamed", 75, Double.NaN, false)
                .clip("Equus-Torpid-Out-Wild", 50, Double.NaN, false)
                .clip("Equus-Trot-Lft", 16, 3.015, true)
                .clip("Equus-Trot-Rit", 16, 3.075, true)
                .clip("Equus-Poop", 25, Double.NaN, false)
                .clip("Equus-Startled", 38, Double.NaN, false)
                .clip("Equus-Hurt-Big-Rit", 25, Double.NaN, false)
                .clip("Equus-Trot-Fwd", 16, 3.187, true)
                .role(ClipRole.HURT, "Equus-Hurt-Big-Rit")
                .role(ClipRole.POOP, "Equus-Poop")
                .role(ClipRole.STARTLE, "Equus-Startled")
                .role(ClipRole.TROT, "Equus-Trot-Fwd")
                .role(ClipRole.TURN_LEFT, "Equus-Trot-Lft")
                .role(ClipRole.TURN_RIGHT, "Equus-Trot-Rit")
                .build());
        BOOKS.put("mammoth", new ClipBook.Builder("mammoth")
                .clip("Mammoth-Idle", 67, Double.NaN, true)
                .clip("Mammoth-Move-Fwd", 40, 0.843, true)
                .clip("Mammoth-Attack-Tusk-Jab", 17, Double.NaN, false)
                .clip("Mammoth-Charge-Fwd", 27, 2.366, true)
                .clip("Mammoth-Graze", 133, Double.NaN, true)
                .clip("Mammoth_new_Call", 61, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Mammoth-Torpid-In", 41, Double.NaN, false)
                .clip("Mammoth-Torpid", 67, Double.NaN, true)
                .clip("Mammoth-Torpid-Eat", 67, Double.NaN, false)
                .clip("Mammoth-Torpid-Out-Tamed", 54, Double.NaN, false)
                .clip("Mammoth-Torpid-Out-Wild", 41, Double.NaN, false)
                .clip("Mammoth-Turn-Lft", 40, Double.NaN, true)
                .clip("Mammoth-Turn-Rit", 40, Double.NaN, true)
                .clip("Mammoth-Poop", 40, Double.NaN, false)
                .clip("Mammoth-Startled", 27, Double.NaN, false)
                .clip("Mammoth-Hurt-Big-Rit", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Mammoth-Hurt-Big-Rit")
                .role(ClipRole.POOP, "Mammoth-Poop")
                .role(ClipRole.STARTLE, "Mammoth-Startled")
                .role(ClipRole.TURN_LEFT, "Mammoth-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Mammoth-Turn-Rit")
                .build());
        BOOKS.put("direwolf", new ClipBook.Builder("direwolf")
                .clip("Direwolf-Idle", 67, Double.NaN, true)
                .clip("Direwolf-Move-Fwd", 15, 4.984, true)
                .clip("Direwolf-Attack-Bite", 20, Double.NaN, false)
                .clip("Direwolf-Charge-Fwd", 12, 6.880, true)
                .clip("Direwolf-Eat", 133, Double.NaN, true)
                .clip("Direwolf-Howl", 93, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Direwolf-Torpid-In", 57, Double.NaN, false)
                .clip("Direwolf-Torpid-Idle", 67, Double.NaN, true)
                .clip("Direwolf-Torpid-Eat", 67, Double.NaN, false)
                .clip("Direwolf-Torpid-Out-Tamed", 60, Double.NaN, false)
                .clip("Direwolf-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Direwolf-Move-Lft", 15, 5.355, true)
                .clip("Direwolf-Move-Rit", 15, 5.113, true)
                .clip("Direwolf-Sniff", 67, Double.NaN, false)
                .clip("Direwolf-Poop", 20, Double.NaN, false)
                .clip("Direwolf-Startled", 43, Double.NaN, false)
                .clip("Direwolf-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Direwolf-Hurt-Big")
                .role(ClipRole.POOP, "Direwolf-Poop")
                .role(ClipRole.SNIFF, "Direwolf-Sniff")
                .role(ClipRole.STARTLE, "Direwolf-Startled")
                .role(ClipRole.TURN_LEFT, "Direwolf-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Direwolf-Move-Rit")
                .build());
        BOOKS.put("sabertooth", new ClipBook.Builder("sabertooth")
                .clip("Saber-Idle", 67, Double.NaN, true)
                .clip("Saber-Move-Fwd", 19, 1.903, true)
                .clip("Saber-Attack-Bite", 20, Double.NaN, false)
                .clip("Saber-Charge-Fwd", 11, 6.560, true)
                .clip("Saber-Eat", 133, Double.NaN, true)
                .clip("Saber-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Saber-Torpid-In", 35, Double.NaN, false)
                .clip("Saber-Torpid-Idle", 67, Double.NaN, true)
                .clip("Saber-Torpid-Eat", 67, Double.NaN, false)
                .clip("Saber-Torpid-Out-Tamed", 53, Double.NaN, false)
                .clip("Saber-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Saber-Turn-Lft", 21, Double.NaN, true)
                .clip("Saber-Turn-Rit", 21, Double.NaN, true)
                .clip("Saber-Poop", 20, Double.NaN, false)
                .clip("Saber-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Saber-Hurt-Big")
                .role(ClipRole.POOP, "Saber-Poop")
                .role(ClipRole.STARTLE, "Saber-Startled")
                .role(ClipRole.TURN_LEFT, "Saber-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Saber-Turn-Rit")
                .build());
        BOOKS.put("megapithecus", new ClipBook.Builder("megapithecus")
                .clip("Gorilla-Idle", 67, Double.NaN, true)
                .clip("Gorilla-Move-Fwd", 27, 2.637, true)
                .clip("Gorilla-Attack-Pound", 27, Double.NaN, false)
                .clip("Gorilla-Charge-Fwd", 11, 9.903, true)
                .clip("Gorilla_Chest_Pounding", 6, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Gorilla-Move-Lft", 27, 2.626, true)
                .clip("Gorilla-Move-Rit", 27, 2.645, true)
                .clip("Gorilla-Hurt-Big", 53, Double.NaN, false)
                .role(ClipRole.HURT, "Gorilla-Hurt-Big")
                .role(ClipRole.TURN_LEFT, "Gorilla-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Gorilla-Move-Rit")
                .build());
        BOOKS.put("paraceratherium", new ClipBook.Builder("paraceratherium")
                .clip("Paraceratherium-Idle", 133, Double.NaN, true)
                .clip("Paraceratherium-Move-Fwd", 35, 1.098, true)
                .clip("Paraceratherium-Attack-Footstomp", 30, Double.NaN, false)
                .clip("Paraceratherium-Charge-Fwd", 17, 3.005, true)
                .clip("Paraceratherium-Eat", 133, Double.NaN, true)
                .clip("Paraceratherium-Startled", 27, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("Paraceratherium-Torpid-In", 40, Double.NaN, false)
                .clip("Paraceratherium-Torpid-Idle", 67, Double.NaN, true)
                .clip("Paraceratherium-Torpid-Eat", 67, Double.NaN, false)
                .clip("Paraceratherium-Torpid-Out-Tamed", 53, Double.NaN, false)
                .clip("Paraceratherium-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("Paraceratherium-Move-Lft", 35, 1.341, true)
                .clip("Paraceratherium-Move-Rit", 35, 1.551, true)
                .clip("Paraceratherium-Poop", 40, Double.NaN, false)
                .clip("Paraceratherium-Hurt-Big-Lft", 20, Double.NaN, false)
                .role(ClipRole.HURT, "Paraceratherium-Hurt-Big-Lft")
                .role(ClipRole.POOP, "Paraceratherium-Poop")
                .role(ClipRole.STARTLE, "Paraceratherium-Startled")
                .role(ClipRole.TURN_LEFT, "Paraceratherium-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "Paraceratherium-Move-Rit")
                .build());
        BOOKS.put("terrorbird", new ClipBook.Builder("terrorbird")
                .clip("TerrorBird-Idle", 67, Double.NaN, true)
                .clip("TerrorBird-Move-Fwd", 17, 1.726, true)
                .clip("TerrorBird-Attack-Bite", 20, Double.NaN, false)
                .clip("TerrorBird-Charge-Fwd", 15, 6.087, true)
                .clip("TerrorBird-Eat", 133, Double.NaN, true)
                .clip("TerrorBird-Startled", 20, Double.NaN, false)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("TerrorBird-Torpid-In", 40, Double.NaN, false)
                .clip("TerrorBird-Torpid-Idle", 67, Double.NaN, true)
                .clip("TerrorBird-Torpid-Eat", 133, Double.NaN, false)
                .clip("TerrorBird-Torpid-Out-Tamed", 53, Double.NaN, false)
                .clip("TerrorBird-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("TerrorBird-Move-Lft", 17, 1.727, true)
                .clip("TerrorBird-Move-Rit", 17, 1.727, true)
                .clip("TerrorBird-Hurt-Big", 20, Double.NaN, false)
                .role(ClipRole.HURT, "TerrorBird-Hurt-Big")
                .role(ClipRole.STARTLE, "TerrorBird-Startled")
                .role(ClipRole.TURN_LEFT, "TerrorBird-Move-Lft")
                .role(ClipRole.TURN_RIGHT, "TerrorBird-Move-Rit")
                .build());
        BOOKS.put("ravager", new ClipBook.Builder("ravager")
                .clip("CaveWolf-Idle", 67, Double.NaN, true)
                .clip("CaveWolf-Walk-Fwd", 20, 2.149, true)
                .clip("CaveWolf-Attack-Bite", 23, Double.NaN, false)
                .clip("CaveWolf-Charge-Fwd", 10, 7.652, true)
                .clip("CaveWolf-Eat", 120, Double.NaN, true)
                .clip("CaveWolf-Howl", 53, Double.NaN, true)
                .clip("Ark-Sleep", 80, Double.NaN, true)
                .clip("CaveWolf-Torpid-In", 47, Double.NaN, false)
                .clip("CaveWolf-Torpid-Idle", 67, Double.NaN, true)
                .clip("CaveWolf-Torpid-Eat", 67, Double.NaN, false)
                .clip("CaveWolf-Torpid-Out-Tamed", 67, Double.NaN, false)
                .clip("CaveWolf-Torpid-Out-Wild", 40, Double.NaN, false)
                .clip("CaveWolf-Walk-Lft", 20, 2.156, true)
                .clip("CaveWolf-Walk-Rit", 20, 2.159, true)
                .clip("CaveWolf-Poop", 30, Double.NaN, false)
                .clip("CaveWolf-Startled", 47, Double.NaN, false)
                .clip("CaveWolf-Hurt", 17, Double.NaN, false)
                .role(ClipRole.HURT, "CaveWolf-Hurt")
                .role(ClipRole.POOP, "CaveWolf-Poop")
                .role(ClipRole.STARTLE, "CaveWolf-Startled")
                .role(ClipRole.TURN_LEFT, "CaveWolf-Walk-Lft")
                .role(ClipRole.TURN_RIGHT, "CaveWolf-Walk-Rit")
                .build());
        BOOKS.put("archaeopteryx", new ClipBook.Builder("archaeopteryx")
                .clip("Archaeopteryx-Idle", 39, Double.NaN, true)
                .clip("Archaeopteryx-Move-Fwd", 16, 0.785, true)
                .clip("Archaeopteryx-Attack-Bite", 13, Double.NaN, false)
                .clip("Archaeopteryx-Charge-Fwd", 10, 1.908, true)
                .clip("Archaeopteryx-Eat", 133, Double.NaN, true)
                .clip("Archaeopteryx-Startle", 39, Double.NaN, true)
                .clip("Archaeopteryx-Fly", 24, Double.NaN, true)
                .clip("Archaeopteryx-Glide", 30, Double.NaN, true)
                .clip("Archaeopteryx-StartPerch", 9, Double.NaN, true)
                .clip("Archaeopteryx-Fly-Startle", 17, Double.NaN, false)
                .clip("Archaeopteryx-Perched", 39, Double.NaN, true)
                .clip("Archaeopteryx-Torpid-In", 66, Double.NaN, false)
                .clip("Archaeopteryx-Torpid-Idle", 66, Double.NaN, true)
                .clip("Archaeopteryx-Torpid-Eat", 53, Double.NaN, false)
                .clip("Archaeopteryx-Torpid-Out-Tamed", 47, Double.NaN, false)
                .clip("Archaeopteryx-Torpid-Out-Wild", 28, Double.NaN, false)
                .clip("Archaeopteryx-Hurt-Big-Rit", 13, Double.NaN, false)
                .role(ClipRole.FLAP, "Archaeopteryx-Fly")
                .role(ClipRole.GLIDE, "Archaeopteryx-Glide")
                .role(ClipRole.HURT, "Archaeopteryx-Hurt-Big-Rit")
                .role(ClipRole.STARTLE, "Archaeopteryx-Startle")
                .build());
        BOOKS.put("quetzal", new ClipBook.Builder("quetzal")
                .clip("Quetzalcoatlus-Ground-Idle", 67, Double.NaN, true)
                .clip("Quetzalcoatlus-Ground-Platform-Move-Fwd", 29, 4.199, true)
                .clip("Quetzalcoatlus-Fly-Attack-Bite", 27, Double.NaN, false)
                .clip("Quetzalcoatlus-Ground-Eat", 67, Double.NaN, true)
                .clip("Quetzalcoatlus-Ground-Startled", 40, Double.NaN, false)
                .clip("Quetzalcoatlus-Fly-Fwd", 33, Double.NaN, true)
                .clip("Quetzalcoatlus-Fly-Flap-Fwd", 67, Double.NaN, true)
                .clip("Quetzalcoatlus-Land-Platform", 47, Double.NaN, false)
                .clip("Quetzalcoatlus-Take-Off-Platform", 47, Double.NaN, false)
                .clip("Quetzalcoatlus-Torpid-In", 33, Double.NaN, false)
                .clip("Quetzalcoatlus-Torpid-Idle", 67, Double.NaN, true)
                .clip("Quetzalcoatlus-Torpid-Eat", 133, Double.NaN, false)
                .clip("Quetzalcoatlus-Torpid-Out-Tamed", 60, Double.NaN, false)
                .clip("Quetzalcoatlus-Torpid-Out-Wild", 33, Double.NaN, false)
                .clip("Quetzalcoatlus-Ground-Hurt-Rit", 20, Double.NaN, false)
                .clip("Quetzalcoatlus-Fly-Idle", 67, Double.NaN, true)
                .role(ClipRole.FLAP, "Quetzalcoatlus-Fly-Flap-Fwd")
                .role(ClipRole.FLY_IDLE, "Quetzalcoatlus-Fly-Idle")
                .role(ClipRole.HURT, "Quetzalcoatlus-Ground-Hurt-Rit")
                .role(ClipRole.STARTLE, "Quetzalcoatlus-Ground-Startled")
                .build());
        BOOKS.put("dragon", new ClipBook.Builder("dragon")
                .clip("Dragon-Ground-Idle", 67, Double.NaN, true)
                .clip("Dragon-Ground-Move-Fwd", 27, 2.531, true)
                .clip("Dragon-Ground-Attack-Bite", 27, Double.NaN, false)
                .clip("Dragon-Ground-Charge-Fwd", 16, 4.840, true)
                .clip("Dragon-Ground-Attack-Fire", 40, Double.NaN, true)
                .clip("Dragon-Fly-Fwd", 27, Double.NaN, true)
                .clip("Dragon-Fly-Idle", 67, Double.NaN, true)
                .clip("Dragon-Land", 33, Double.NaN, false)
                .clip("Dragon-Take-Off", 33, Double.NaN, false)
                .clip("Dragon-Fly-Attack-Swoop-Out", 27, Double.NaN, false)
                .clip("Dragon-Fly-Attack-Fire", 42, Double.NaN, true)
                .clip("Dragon-Ground-Turn-Lft", 30, Double.NaN, true)
                .clip("Dragon-Ground-Turn-Rit", 30, Double.NaN, true)
                .clip("Dragon-Fly-Lft", 27, Double.NaN, true)
                .clip("Dragon-Fly-Rit", 27, Double.NaN, true)
                .role(ClipRole.FLY_IDLE, "Dragon-Fly-Idle")
                .role(ClipRole.FLY_LEFT, "Dragon-Fly-Lft")
                .role(ClipRole.FLY_RIGHT, "Dragon-Fly-Rit")
                .role(ClipRole.TURN_LEFT, "Dragon-Ground-Turn-Lft")
                .role(ClipRole.TURN_RIGHT, "Dragon-Ground-Turn-Rit")
                .build());
    }

    /** The clip book of a registry id; an empty book when the species has no runtime clips. */
    public static ClipBook of(String species) {
        return BOOKS.getOrDefault(species, ClipBook.EMPTY);
    }

    private BehaviorClips() {}
}
